// examples/nextjs/pages/basic.jsx
import MuxPlayer from '@mux/mux-player-react';
import muxBlurHash from '@mux/blurhash';

const Basic = ({ playbackId, blurHashBase64, sourceWidth, sourceHeight }) => (
	<MuxPlayer
		streamType="on-demand"
		playbackId={playbackId}
		placeholder={blurHashBase64}
		style={{ aspectRatio: `${sourceWidth / sourceHeight}` }}
		metadata={{
			video_id: 'video-id-54321',
			video_title: 'Test video title',
			viewer_user_id: 'user-id-007'
		}}
	/>
);

export const getStaticProps = async () => {
	const playbackId = '23s11nz72DsoN657h4314PjKKjsF2JG33eBQQt6B95I';
	const { blurHashBase64, sourceWidth, sourceHeight } = await muxBlurHash(playbackId);

	return {
		props: {
			playbackId,
			blurHashBase64,
			sourceWidth,
			sourceHeight
		}
	};
};

export default Basic;

// examples/sveltekit/src/routes/basic/+page.svelte
<script lang="ts">
	import '@mux/mux-player';

	import type { PageData } from './$types';

	export let data: PageData;
</script>

<main>
	<mux-player
	stream-type="on-demand"
	playback-id={data.playbackId}
	metadata-video-title="Test VOD"
	metadata-viewer-user-id="user-id-007"
	placeholder={data.blurHashBase64}
	style:aspect-ratio={data.sourceWidth / data.sourceHeight}
	/>
</main>
